### ISSUE TITLE
irods could not receive server response

### ISSUE THREAD

**Issue by tvkent** [lntran26/donni#17]
Testing a 3D model fit with 20 samples in each population. Models for parameters download, and sometimes the pngs download as well, before getting the following error. Tested on a cluster and locally with the same error. I've seen this for the split_nomig, sim_split_no_mig_size, and sim_split_refugia_sym_mig_all models from Portik et al., but have had success with other Portik models. Any ideas?

CRITICAL:irods.connection:timed out
ERROR:irods.connection:Could not receive server response
Traceback (most recent call last):
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/connection.py", line 114, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/message/__init__.py", line 270, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/message/__init__.py", line 180, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tvkent/anaconda3/envs/donni/bin/donni", line 8, in <module>
    sys.exit(main())
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/donni/__main__.py", line 586, in main
    args.func(args)
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/donni/__main__.py", line 255, in run_infer
    args.mlpr_dir, qc_dir = irods_download(args.model, ss, args.folded, args.download_dir)
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/donni/infer.py", line 104, in irods_download
    session.data_objects.get(model.path, datadir, force=True)
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/manager/data_object_manager.py", line 122, in get
    self._download(path, local_path, num_threads = num_threads, **options)
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/manager/data_object_manager.py", line 99, in _download
    with open(local_file, 'wb') as f, self.open(obj, 'r', **options) as o:
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/manager/data_object_manager.py", line 340, in open
    desc = conn.recv().int_info
  File "/Users/tvkent/anaconda3/envs/donni/lib/python3.9/site-packages/irods/connection.py", line 125, in recv
    raise NetworkException("Could not receive server response")
irods.exception.NetworkException: Could not receive server response

**Comment by tjstruck** [comment]
Hi @tvkent, it might have been a bug that occurred when a few of the parameter models were uploaded. I could reproduce the error you got, and updating the files that seemed problematic fixed the issue for me. 

If you are still running into an error, let us know. It would also be helpful to know if it is consistent on where in downloading parameter models run into an issue. Ex for `split_nomig`, I kept getting an error when downloading `param_04_predictor`:

```
Downloading model: /iplant/home/shared/donni/split_nomig/unfolded/ss_20_20_20/v0.0.1/tuned_models/param_01_predictor to /Users/tjstruck/Library/Caches/donni/0.0.1/split_nomig_unfolded_ns_20_20_20
Downloading model: /iplant/home/shared/donni/split_nomig/unfolded/ss_20_20_20/v0.0.1/tuned_models/param_02_predictor to /Users/tjstruck/Library/Caches/donni/0.0.1/split_nomig_unfolded_ns_20_20_20
Downloading model: /iplant/home/shared/donni/split_nomig/unfolded/ss_20_20_20/v0.0.1/tuned_models/param_03_predictor to /Users/tjstruck/Library/Caches/donni/0.0.1/split_nomig_unfolded_ns_20_20_20
Downloading model: /iplant/home/shared/donni/split_nomig/unfolded/ss_20_20_20/v0.0.1/tuned_models/param_04_predictor to /Users/tjstruck/Library/Caches/donni/0.0.1/split_nomig_unfolded_ns_20_20_20
CRITICAL:irods.connection:timed out
ERROR:irods.connection:Could not receive server response
```

**Comment by tjstruck** [comment]
I've tested all our models and configurations and am not getting this error on them. @tvkent , it would be good to know if you are still running into this issue so I can know if I need to do further testing. Also, if you are still having issues and you are using a script, it would be helpful to get a copy if you are okay with providing one.

**Comment by tvkent** [comment]
@tjstruck hey, yes this seems to have fixed the problem. I haven't run into any models with this error since your fix. thanks!
